name: "TS action"

inputs:
  run:
    description: "Start action in directory"
    required: true
  node-version:
    description: "Node version to use"
    required: false
    default: "22"
  inputs:
    description: "Inputs to pass to the action"
    required: false

runs:
  using: composite
  steps:
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: build action js
      shell: bash
      working-directory: ${{ inputs.run }}
      run: |
        echo "Building action in ${{ inputs.run }}"
        npm install
        npm run build

# cache

    - name: js run
      uses: ${{ inputs.start }}/dist@${{ github.ref_name }}
      with:
        message: something something
