name: "TS action"

inputs:
  run:
    description: "Start action in directory"
    required: true
  node-version:
    description: "Node version to use"
    required: false
    default: "20"
  args:
    description: "Inputs to pass to the action"
    required: false

runs:
  using: composite
  steps:
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: cache built action
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.run }}/dist
        key: ${{ inputs.run }}-dist-${{ runner.os }}-${{ hashFiles(format('{0}/**', inputs.run)) }}

    - name: build action js
      shell: bash
      working-directory: ${{ inputs.run }}
      run: |
        echo "Building action in ${{ inputs.run }}"
        npm install
        npm run build


    - name: js run
      uses: ${{ inputs.run }}/dist@${{ github.ref_name }}
      with:
        message: something something
