name: "TS action"

inputs:
  run:
    description: "Start action in directory"
    required: true
  node-version:
    description: "Node version to use"
    required: false
    default: "20"
  args:
    description: "Inputs to pass to the action"
    required: false

runs:
  using: composite
  steps:
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: cache built action
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.run }}/dist
        key: ${{ inputs.run }}-dist-${{ runner.os }}-${{ hashFiles(format('{0}/**', inputs.run)) }}

    - name: build action js
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: ${{ inputs.run }}
      run: |
        echo "Building action in ${{ inputs.run }}"
        npm install
        npm run build

    - name: debug
      shell: bash
      working-directory: ${{ inputs.run }}/dist
      run: |
        ls -al 

    - uses: jenseng/dynamic-uses@v1
      name: js run
      with:
        # now you can use expressions 🥳
        uses: ${{ inputs.run }}/dist
        with: |
          {
            "message": "something something"
          }
