name: Manual workflow test

on:
  workflow_dispatch:
    inputs: {}
  push: {}

jobs:
  first:
    runs-on: my-custom-runner
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: prepare local actions
        uses: ./.github/actions/ts-action-build

      - name: Local TS action
        uses: ./.github/actions/some-ts-action
        with:
          message: "Hello world"